import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DefaultSidebar } from "./components/sidebar";
import { NavbarWithMegaMenu } from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-[100%] h-[100vh] flex overflow-hidden">
          <DefaultSidebar />
          <div className="flex-1 flex gap-4">
            <main className="flex-1 p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
